spring:
  application:
    name: MyCityGov

  datasource:
    url: jdbc:h2:file:./LOCAL_DATA/h2/app;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
    username: me
    password: changeme
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

#MINIO CONFIGURATION
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET}

#TWILIO CONFIGURATION
twilio:
  account-sid: ${TWILIO_SID}
  auth-token: ${TWILIO_TOKEN}
  phone-number: ${TWILIO_PHONE}

gov:
  api:
    url: http://localhost:8081/api/external/gov-login